version: '3'

services:
  app-1:
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3001:3000
    links:
      - mongo:mongo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://mongo:27017/crowi-1
      - REDIS_URL=redis://redis:6379/crowi-1
      - ELASTICSEARCH_URI=http://elasticsearch:9200/crowi-1
      - PASSWORD_SEED=changeme
    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://redis:6379
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - crowi_data_1:/data

  app-2:
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3002:3000
    links:
      - mongo:mongo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://mongo:27017/crowi-2
      - REDIS_URL=redis://redis:6379/crowi-2
      - ELASTICSEARCH_URI=http://elasticsearch:9200/crowi-2
      - PASSWORD_SEED=changeme
    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://redis:6379
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - crowi_data_2:/data

  app-3:
    image: "crowiplusmulti_app:latest"
    ports:
      - 127.0.0.1:3003:3000
    links:
      - mongo:mongo
      - redis:redis
      - elasticsearch:elasticsearch
    depends_on:
      - mongo
      - redis
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://mongo:27017/crowi-3
      - REDIS_URL=redis://redis:6379/crowi-3
      - ELASTICSEARCH_URI=http://elasticsearch:9200/crowi-3
      - PASSWORD_SEED=changeme
    command: "dockerize
              -wait tcp://mongo:27017
              -wait tcp://redis:6379
              -wait tcp://elasticsearch:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - crowi_data_3:/data

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  redis:
    image: redis:3-alpine
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:5.3-alpine
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # decrease amount or just comment out this line if you cannot allocate enough memory
    command:
      - sh
      - -c
      - "./bin/elasticsearch-plugin list | grep -q analysis-kuromoji || ./bin/elasticsearch-plugin install analysis-kuromoji;
        ./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu;
        /docker-entrypoint.sh elasticsearch"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins
      - ./esconfig:/usr/share/elasticsearch/config

volumes:
  crowi_data_1:
  crowi_data_2:
  crowi_data_3:
  mongo_configdb:
  mongo_db:
  redis_data:
  es_data:
  es_plugins:
